FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD alembic upgrade head && gunicorn -w 4 -b 0.0.0.0:8000 --reload "app:create_app()"
