"""add vuln_cache table

Revision ID: 31fb552ab2d0
Revises: 9921f2469b40
Create Date: 2026-05-19 23:40:27.905437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31fb552ab2d0'
down_revision: Union[str, None] = '9921f2469b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vuln_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(length=30), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vuln_cache_cve_id'), 'vuln_cache', ['cve_id'], unique=True)
    op.create_index(op.f('ix_vuln_cache_id'), 'vuln_cache', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vuln_cache_id'), table_name='vuln_cache')
    op.drop_index(op.f('ix_vuln_cache_cve_id'), table_name='vuln_cache')
    op.drop_table('vuln_cache')
    # ### end Alembic commands ###
